-- Mithora Kitchen LOCAL MENU TEST SEED
-- Extracted from existing SQL dump.
-- Includes all rows for requested tables.

PRAGMA foreign_keys = OFF;

-- kitchen_settings (1 rows)
INSERT INTO "kitchen_settings" ("id","kitchen_open_time","kitchen_close_time","global_cutoff_minutes","prep_time_default_minutes","next_day_cutoff_time","allow_subscriptions","timezone","created_at","updated_at") VALUES(1,'09:00','11:00',20,20,'23:30',1,'Asia/Kolkata','2026-01-21 13:01:40','2026-01-21 13:01:40');

-- delivery_slots (8 rows)
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(1,'Breakfast','09:00','10:30','09:30','11:30',1,'2026-01-18 07:54:52','2026-01-18 07:54:52',30);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(2,'Lunch','09:30','11:00','13:00','15:00',1,'2026-01-18 07:55:34','2026-01-18 07:55:34',10);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(3,'Dinner','09:30','18:00','19:00','20:00',1,'2026-01-18 07:56:52','2026-01-18 07:56:52',15);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(4,'Morning1','09:00','10:30','11:30','12:00',1,'2026-01-23 08:08:16','2026-01-23 08:08:16',30);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(5,'Morning2','11:00','12:00','13:00','14:00',1,'2026-01-23 08:08:58','2026-01-23 08:08:58',30);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(6,'Noon1','13:00','14:00','14:30','15:30',1,'2026-01-23 08:09:38','2026-01-23 08:09:38',30);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(7,'Noon2','15:00','16:30','17:00','18:00',1,'2026-01-23 08:10:51','2026-01-23 08:10:51',30);
INSERT INTO "delivery_slots" ("id","name","order_start_time","order_end_time","delivery_start_time","delivery_end_time","is_active","created_at","updated_at","cutoff_minutes") VALUES(8,'Evening1','17:00','18:30','19:00','20:30',1,'2026-01-23 08:54:36','2026-01-23 08:54:36',30);

-- categories (8 rows)
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(1,'Breakfast','light-breakfast','Homemade Fresh Breakfast','local',0,0,1,30,25,0,0,NULL,NULL,0,1,'2026-01-18 07:57:32','2026-09-13 15:44:28','https://assets.mithora.in/images/aloo-methi.webp');
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(2,'All-Day Meal','lunch','Homemade Lunch','local',0,0,1,45,25,0,0,NULL,NULL,0,1,'2026-01-18 07:58:13','2026-04-22 01:56:30',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(4,'Daily Tiffin','homemade-tiffin','Homemade Tiffin Subscription','local',0,1,1,60,0,0,0,NULL,NULL,0,1,'2026-01-18 07:59:00','2026-09-13 15:44:28',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(5,'Snacks','homemade-snacks','Homemade Fresh Snacks','local',0,0,0,20,20,0,1,NULL,NULL,0,1,'2026-01-18 07:59:41','2026-09-13 15:44:28',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(7,'Travel Meal','travel-food-train-bus-journey','Freshly prepared homemade meals packed for train and bus journeys, cooked light, sealed hygienically, and best enjoyed within 6–8 hours.','local',0,0,0,20,20,0,1,NULL,NULL,0,1,'2026-01-26 09:44:50','2026-09-13 15:44:28',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(8,'Party Order','party-order','Bulk order for Party','local',0,0,0,20,20,0,1,NULL,NULL,0,1,'2026-01-28 14:04:40','2026-04-22 01:55:03',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(9,'Vrat Special','vrat-special','','local',0,0,0,60,30,0,0,NULL,NULL,0,1,'2026-03-10 02:28:05','2026-04-22 01:55:03',NULL);
INSERT INTO "categories" ("id","name","slug","description","shipping_type","is_local_only","subscription_allowed","slot_wise","prep_time_minutes","delivery_time_minutes","cutoff_minutes","next_day_delivery","slot_start","slot_end","min_order_amount","is_active","created_at","updated_at","image_path") VALUES(10,'Fruit & Sprouts','fruit-sprouts','Healthy Fruit Bowl & Sprouts','local',0,0,0,30,20,0,0,NULL,NULL,0,1,'2026-03-11 14:24:19','2026-04-22 01:56:30',NULL);

-- category_slots (8 rows)
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(1,1);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(2,4);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(4,3);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(4,2);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(2,7);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(2,5);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(2,6);
INSERT INTO "category_slots" ("category_id","slot_id") VALUES(2,8);

-- products (43 rows)
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(1,'fresh-indori-poha','Fresh Poha','poha','Light & fluffy Indori-style breakfast.',1,1,1,'/images/menu/breakfast/poha.webp','2026-01-18 08:01:16','2026-09-12 11:09:28');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(2,'rava-upma','Upma','upma','Soft, warm and homely rava upma.',1,1,0,'/images/menu/breakfast/upma.webp','2026-01-18 08:14:06','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(3,'besan-pyaz-bread-toast','Besan Pyaz Bread Toast','besan-pyaz-bread-toast','Besan and onion dipped bread nicely toasted.',1,0,1,'/images/menu/breakfast/besan-pyaz-bread-toast.webp','2026-01-18 08:16:12','2026-09-12 11:42:23');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(4,NULL,'Poori Aloo',NULL,'Garam poori with aloo bhaji — tomato rich gravy in festive style.',1,1,0,'/images/menu/breakfast/aloo-puri-bhaji.webp','2026-01-18 08:17:45','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(5,NULL,'Aaloo Paratha',NULL,'Stuffed with spiced mashed potato filling and cooked with ghee or oil.',1,0,0,'/images/menu/breakfast/aaloo-paratha.webp','2026-01-18 08:19:26','2026-05-01 02:05:07');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(6,NULL,'Rajma Chawal',NULL,'Slow-cooked rajma with steamed chawal.',2,0,1,'/images/menu/all-day-meal/rajma.webp','2026-01-18 08:21:12','2026-09-12 11:42:23');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(7,NULL,'Dal Khichdi',NULL,'A blend of rice and dal with mild spices.',2,1,0,'/images/menu/all-day-meal/dal-khichadi.webp','2026-01-18 08:22:20','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(8,NULL,'Soya Chunk Biryani',NULL,'Nutritious biryani made with fragrant rice and soya chunks.',2,0,1,'/images/menu/all-day-meal/soya-chunks-biryani.webp','2026-01-18 10:59:18','2026-09-12 11:42:23');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(9,NULL,'Homemade Pure Veg Thali',NULL,'Roti, sabji, dal & rice — simple & homely.',2,1,0,'/images/menu/all-day-meal/roti.webp','2026-01-18 11:00:42','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(10,NULL,'Pav Bhaji',NULL,'Pav (3 pcs) with bhaji, served with onion & lemon.',2,0,0,'/images/menu/all-day-meal/pav-bhaji.webp','2026-01-18 11:02:55','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(11,NULL,'Dal Fry',NULL,'Dal cooked in ghee with fresh onion, tomato, garlic & ginger. Topped with fresh green coriander.',2,1,1,'/images/menu/all-day-meal/dal-fry.webp','2026-01-18 11:05:53','2026-09-12 12:51:46');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(12,NULL,'Gatta Masala',NULL,'Rajasthani besan gatta in a soft and thick gravy, medium spicy. Topped with fresh coriander.',2,0,0,'/images/menu/all-day-meal/gatta-masala.webp','2026-01-18 11:07:22','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(13,NULL,'Aloo Methi',NULL,'Seasonal fresh methi (fenugreek) prepared with aloo and mild spices.',2,0,1,'/images/menu/all-day-meal/aloo-methi-sabzi-homemade.webp','2026-01-18 11:08:39','2026-09-12 11:42:23');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(14,NULL,'Aloo Palak',NULL,'Fresh palak (spinach) prepared with aloo and mild spices.',2,0,0,'/images/menu/all-day-meal/aloo-palak.webp','2026-01-18 11:09:57','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(15,NULL,'Sev Tamatar',NULL,'Sev namkeen tossed with diced onion & tomato in home-style spices.',2,0,0,'/images/menu/all-day-meal/sev-tamatar.webp','2026-01-18 11:11:34','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(16,NULL,'Kadhai Paneer',NULL,'Paneer cooked in thick onion-tomato gravy with capsicum and fresh coriander.',2,0,0,'/images/menu/all-day-meal/kadhai-paneer.webp','2026-01-18 11:12:45','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(17,NULL,'Roti',NULL,'Fresh tawa roti — 1 pc.',2,1,0,'/images/menu/all-day-meal/tawa-roti.webp','2026-01-18 11:13:51','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(18,NULL,'Tiffin Box  ( Delight )',NULL,replace(replace('Fresh homemade tiffin with 4 roti, 2 sabzi( Gravy & Dry ), dal, jeera rice, Salad, Raita/Chaas,Papad,Sweet. Light, healthy daily meals delivered hot.\r\n(Monday - Saturday)','\r',char(13)),'\n',char(10)),4,1,0,'/images/menu/tiffin/mithora-tiffin-services.webp','2026-01-18 11:16:15','2026-02-24 03:30:21');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(19,NULL,'Tiffin Box Weekly',NULL,replace(replace('Fresh homemade tiffin with roti, sabzi, dal and rice. Light, healthy daily meals delivered hot.\r\n(Monday - Saturday)','\r',char(13)),'\n',char(10)),4,1,0,'/images/menu/tiffin/mithora-tiffin-services.webp','2026-01-18 11:17:29','2026-01-30 12:51:27');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(20,NULL,'Tiffin Box Monthly',NULL,'Fresh homemade tiffin with roti, sabzi, dal and rice. Light, healthy daily meals delivered hot.',4,1,0,'/images/menu/tiffin/mithora-tiffin-services.webp','2026-01-18 11:18:39','2026-01-24 07:03:01');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(21,NULL,'Litti Chokha',NULL,'Homemade litti chokha(Baingan Bharta ) prepared in authentic Bihar–Purvanchal style.',2,0,0,'/images/menu/all-day-meal/litti-chokha-jaipur.webp','2026-01-21 03:23:18','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(22,NULL,'Sattu Paratha',NULL,'Sattu-stuffed paratha, tawa-roasted.',2,0,0,'/images/menu/all-day-meal/sattu-paratha.webp','2026-01-21 03:26:23','2026-05-01 02:16:05');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(23,NULL,'Dal Bati Churma',NULL,'Rajasthani pure & fresh homemade Dal Bati Churma.',2,1,0,'/images/menu/all-day-meal/dal-bati-churma-jaipur.webp','2026-01-21 03:28:09','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(24,NULL,'Homemade Mathri',NULL,'Homemade Crispy Mathri',5,1,0,'/images/menu/snacks/mathari.webp','2026-01-21 03:38:46','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(25,NULL,'Chini Petha',NULL,'Homemade Chini Petha, best traditional sweet.',5,1,0,'/images/menu/snacks/chini-petha.webp','2026-01-21 03:42:58','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(26,NULL,'Chana Dal Namkeen',NULL,'Fresh & Pure homemade Chana Dal Namkeen',5,1,0,'/images/menu/snacks/chan-daal-namkeen.webp','2026-01-21 03:44:41','2026-01-24 06:55:47');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(27,NULL,'Vada Pav',NULL,'Soft pav stuffed with a crispy, spiced potato vada, served with fresh coriander (dhaniya) chutney.',2,0,0,'/images/menu/all-day-meal/vada-pav.webp','2026-01-23 07:41:15','2026-05-01 02:16:44');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(28,NULL,'Veg Cheesy Sandwich',NULL,'Veg Cheese Sandwich',2,0,0,'/images/menu/all-day-meal/fresh-veg-cheese-sandwich.webp','2026-01-23 08:04:24','2026-05-01 02:16:44');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(29,NULL,'Gola Rice Marathi Style',NULL,'Gola Rice Kadhi (Marathi Style) 🍚🥣',2,0,0,'/images/menu/all-day-meal/gola-kadhi-rice-marathi-style.webp','2026-01-26 04:41:14','2026-05-01 02:16:44');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(30,NULL,'Travel Meal',NULL,'Fresh homemade food packed specially for train & bus journeys',7,1,0,'/images/menu/travel-food/travel-meal.webp','2026-01-26 09:53:17','2026-01-26 09:53:17');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(31,NULL,'Party Food Order',NULL,'Pure Veg, Party Bulk food Order for 10-15 person.',8,1,0,'/images/menu/party-thali-for-10-15/birthday-office-party-thali-10-15-person.webp','2026-01-28 14:06:14','2026-01-28 14:36:58');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(32,NULL,'Pav Bhaji Party Special',NULL,'Freshly prepared butter pav bhaji cooked slow in our home kitchen using premium vegetables and house spices.',8,1,0,'/images/menu/party-thali-for-10-15/pav-bhaji.webp','2026-01-31 07:48:17','2026-01-31 08:06:58');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(33,NULL,'Chole Aloo Poori Festive Special',NULL,'Classic North Indian chole paired with lightly spiced aloo sabji and fresh hot pooris.',8,1,0,'/images/menu/party-thali-for-10-15/aloo-puri-bhaji.webp','2026-01-31 07:53:00','2026-01-31 08:07:45');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(36,NULL,'Tiffin Box (Regular)',NULL,'Fresh homemade tiffin with 4 roti, sabzi, dal, rice, Salad. Light, healthy daily meals delivered hot. (Monday - Saturday)',4,1,0,'/images/mithora-tiffin-services.jpeg','2026-02-24 03:31:16','2026-02-24 04:12:13');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(37,NULL,'Tiffin Box Combo ( Lunch & Dinner )',NULL,'Fresh homemade tiffin combo Lunch & Dinner. Light, healthy daily meals delivered hot.',4,1,0,'/images/mithora-tiffin-services.jpeg','2026-02-24 03:34:04','2026-02-24 03:34:04');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(38,NULL,'Dal Bati Special',NULL,'Rajasthani pure & fresh homemade Dal Bati Churma.',8,1,0,'/images/menu/all-day-meal/dal-bati-churma-jaipur.webp','2026-03-10 02:21:36','2026-03-10 02:21:36');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(39,NULL,'Sabudana Classics',NULL,replace(replace('Sabudana Khichdi: Non-sticky & peanut-rich. Sabudana Vada: Crispy outside, soft inside. Served with fresh Chutney / Dahi.\r\n','\r',char(13)),'\n',char(10)),9,1,0,'/images/sabudana-khichdi-dahi.webp','2026-03-10 02:29:24','2026-03-10 02:30:52');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(40,NULL,'Vrat Thali',NULL,replace(replace('3 Rajgiri / Kuttu Ki Roti:\r\nFreshly made.\r\nMain:\r\nVrat Wale Alloo Ki Sabji.\r\nSides:\r\nDahi & Sabudana Khichdi.\r\nDessert:\r\nShudh Alloo Ka Halwa.','\r',char(13)),'\n',char(10)),9,1,0,'/images/vrat-thali.webp','2026-03-10 02:31:58','2026-03-10 02:31:58');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(41,NULL,'Fast Food Combo',NULL,'Perfect Fast Food Combo Option for kitty Party, Birthday Party, Home party, Family Gatherings.',8,1,0,'/images/menu/fast-food/fastfood-light.png','2026-03-10 02:41:04','2026-03-10 02:47:32');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(42,NULL,'Fruit Bowl',NULL,'A hand-picked selection of Apple, Pomegranate, Papaya, Kiwi, and seasonal fruits like Mango. Topped with seeds.',10,1,0,'/images/fruit-bowl-jaipur.webp','2026-03-11 14:25:36','2026-03-14 09:32:38');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(43,NULL,'Sprouts Bowl',NULL,'Protein-rich Moong and Chana sprouts prepared in our home kitchen. Mixed with lemon, onion, and mild spices.',10,0,0,'/images/sprouts-salad-jaipur.webp','2026-03-11 14:27:14','2026-05-01 02:18:13');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(44,NULL,'Pindi Chole with 2 Paratha',NULL,'Punjabi-style pindi chole served with 2 freshly made ghee paratha  – bold, flavorful, and satisfying.',2,1,0,'/images/menu/all-day-meal/Pindi-chole.webp','2026-05-01 02:19:43','2026-05-01 02:27:34');
INSERT INTO "products" ("id","sku","name","slug","description","category_id","is_active","is_featured","image_path","created_at","updated_at") VALUES(45,NULL,'Paneer Butter Masala Paratha Combo',NULL,'Flavorful paneer butter masala with rich gravy, served with 2 warm paratha – a perfect comfort meal.',2,1,0,'/images/menu/all-day-meal/Butter-Paneer-Masala.webp','2026-05-01 02:22:01','2026-05-01 02:27:02');

-- product_variants (55 rows)
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(1,1,'Indori Poha','Light & fluffy Indori-style breakfast.',80,0,1,'local',200,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:02:48','2026-05-02 05:08:29');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(2,2,'Rava Upma','Soft, warm and homely rava upma.',80,0,0,'local',200,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:14:52','2026-05-02 05:09:11');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(3,3,'Besan Pyaz Bread Toast','Besan and onion dipped bread nicely toasted.',60,75,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:16:55','2026-01-18 08:16:55');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(4,4,'Poori Aloo','Garam poori with aloo bhaji — tomato rich gravy in festive style.',99,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:18:24','2026-01-18 08:18:24');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(5,5,'Aaloo Paratha','Stuffed with spiced mashed potato filling and cooked with ghee or oil.',99,120,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:20:02','2026-01-18 08:20:02');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(6,6,'Rajma Chawal','Slow-cooked rajma with steamed chawal.',125,150,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:21:45','2026-01-18 08:21:45');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(7,7,'Dal Khichdi','A blend of rice and dal with mild spices.',99,149,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 08:22:46','2026-01-18 08:22:46');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(8,8,'Soya Chunk Biryani','Nutritious biryani made with fragrant rice and soya chunks.',235,270,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 10:59:49','2026-01-18 10:59:49');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(9,9,'Halka Fulka Thali','Roti, sabji, dal & rice — simple & homely.',149,199,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:01:29','2026-01-18 11:01:29');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(10,10,'Pav Bhaji','Pav (3 pcs) with bhaji, served with onion & lemon.',150,190,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:04:06','2026-01-18 11:04:06');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(11,11,'Dal Fry','Dal cooked in ghee with fresh onion, tomato, garlic & ginger. Topped with fresh green coriander.',180,200,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:06:34','2026-01-18 11:06:34');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(12,12,'Gatta Masala','Rajasthani besan gatta in a soft and thick gravy, medium spicy. Topped with fresh coriander.',170,200,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:07:57','2026-01-18 11:07:57');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(13,13,'Aloo Methi','Seasonal fresh methi (fenugreek) prepared with aloo and mild spices.',100,130,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:09:10','2026-01-18 11:09:10');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(14,14,'Aloo Palak','Fresh palak (spinach) prepared with aloo and mild spices.',130,150,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:10:58','2026-01-18 11:10:58');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(15,15,'Sev Tamatar','Sev namkeen tossed with diced onion & tomato in home-style spices.',150,180,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:12:08','2026-01-18 11:12:08');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(16,16,'Kadhai Paneer','Paneer cooked in thick onion-tomato gravy with capsicum and fresh coriander.',250,280,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:13:15','2026-01-18 11:13:15');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(17,17,'Roti Plain','Plain Roti 1 Pc',15,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:14:37','2026-01-18 11:14:37');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(18,17,'Roti Ghee','Ghee Roti 1 Pc',25,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:15:03','2026-01-18 11:15:03');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(19,18,'Tiffin Box','Fresh homemade tiffin with roti, sabzi, dal and rice. Light, healthy daily meals delivered hot.',180,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:16:43','2026-06-24 02:13:18');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(20,19,'Mithora Standard Tiffin',replace(replace('Fresh homemade tiffin with roti, sabzi, dal and rice. Light, healthy daily meals delivered hot.\r\n(Monday - Saturday)','\r',char(13)),'\n',char(10)),900,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:18:13','2026-06-24 02:13:18');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(21,20,'Mithora Regular Tiffin','Fresh homemade tiffin with 4 roti, sabzi, dal, rice, Salad. Light, healthy daily meals delivered hot. (Monday - Saturday)',3500,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:20:17','2026-02-24 03:53:17');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(22,20,'Mithora Delight Tiffin',replace(replace('Fresh homemade tiffin with 4 roti, 2 sabzi( Gravy & Dry ), dal, jeera rice, Salad, Raita/Chaas,Papad,Sweet. Light, healthy daily meals delivered hot.\r\n(Monday - Saturday)','\r',char(13)),'\n',char(10)),4000,4250,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:20:56','2026-02-24 03:58:50');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(23,19,'Mithora Delight Tiffin',replace(replace('Fresh homemade tiffin with 4 roti, 2 sabzi( Gravy & Dry ), dal, jeera rice, Salad, Raita/Chaas,Papad,Sweet. Light, healthy daily meals delivered hot.\r\n(Monday - Saturday)','\r',char(13)),'\n',char(10)),950,0,0,'local',0,0,0,0,0,0,1,'none',0,0,NULL,NULL,1,'2026-01-18 11:21:50','2026-02-24 03:59:08');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(24,21,'Litti Chokha','Homemade fresh 2 Pc Saatu litti with Baingan Bharta.',200,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:23:58','2026-01-21 03:25:10');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(25,22,'Sattu Paratha','2 Pc Sattu paratha served with Dahi and chokha',150,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:27:07','2026-01-21 03:27:07');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(26,23,'Dal Bati Churma','4 Pc Bati, Dal with Churma & Raita.',350,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:28:47','2026-01-21 03:28:47');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(27,24,'500 Gm','Freshly Prepared Mathri Pack',195,250,0,'local',500,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:41:40','2026-01-29 16:39:03');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(28,25,'500 Gm','Fresh Chini Petha',220,0,0,'local',500,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:43:52','2026-01-21 03:43:52');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(29,26,'500 Gm','Chana Dal Namkeen Pack',230,0,0,'local',500,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-21 03:45:27','2026-01-21 03:45:27');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(30,27,'Vada Pav','Mumbai’s iconic street snack — a spicy potato fritter (vada) tucked inside a soft bun (pav), topped with fiery dhaniya chutney. Simple, crunchy, and irresistibly delicious. 🌶️🥔🍞',20,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-23 07:42:20','2026-01-23 07:57:54');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(31,28,'Veg Cheese Sandwich🌿🌶️','A wholesome sandwich loaded with fresh capsicum, onion, and tomato, layered with melted cheese and mild spices. Grilled to perfection — crunchy outside, cheesy and flavorful inside. 🥪🧀',50,70,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-23 08:06:30','2026-01-23 08:06:30');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(32,29,'Gola Rice with Kadhi','A traditional Marathi comfort dish🍚🥣 with soft steamed toor dal gola (pakoda) served alongside fluffy rice and mildly spiced yogurt–gram flour kadhi. Light, tangy, and soothing with authentic Maharashtrian home-style flavors.',200,0,0,'local',0,0,0,0,0,0,1,'none',0,0,NULL,NULL,1,'2026-01-26 04:42:50','2026-03-16 11:31:46');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(33,30,'Train Pack','Freshly prepared homemade meals packed for train and bus journeys, cooked light, sealed hygienically, and best enjoyed within 6–8 hours.',150,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-26 09:54:31','2026-01-26 09:54:31');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(34,30,'Family Thali for 4','10 whole-wheat rotis served with a large portion of freshly prepared 2 sabji,dal,rice etc.suitable for 4 people. A complete homestyle meal for family dining.',500,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-26 09:57:22','2026-01-26 09:57:22');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(35,30,'Bus Pack for 2','5-6 rotis with generously portioned sabji (serves 2) — light, filling, and packed hygienically for group meals or travel.',280,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-01-26 09:58:19','2026-01-26 09:58:19');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(36,31,'Homestyle Basic',replace(replace('Per Person Menu Details\r\n\r\n3-4 Roti • 1 Rice • 2 Sabji • 1 Dal • 1 Raita & Salad','\r',char(13)),'\n',char(10)),180,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-28 14:09:06','2026-06-24 02:09:37');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(37,32,'Pav Bhaji Party Special',replace(replace('Served with soft pav and classic accompaniments. A proven crowd favorite for birthdays and kids’ parties.\r\n\r\nIncludes:\r\n• Pav Bhaji – ~2.5 kg\r\n• Butter Pav – 50 pcs\r\n• Onion, lemon & butter – included\r\n\r\nSuitable for: Birthday parties, kids events, casual gatherings','\r',char(13)),'\n',char(10)),2400,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-31 07:49:09','2026-01-31 08:22:23');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(38,33,'Chole Aloo Poori',replace(replace('Filling, festive, and perfect for morning functions and pooja bhog. Satvik option available.\r\n\r\nIncludes:\r\n• Chole – ~2.5 kg\r\n• Aloo Sabji – ~1 kg\r\n• Poori – ~40 pcs','\r',char(13)),'\n',char(10)),2250,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-01-31 07:53:40','2026-01-31 08:20:43');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(41,36,'Mithora Standard Tiffin','Fresh homemade tiffin with 4 roti, sabzi, dal, rice, Salad. Light, healthy daily meals delivered hot. (Monday - Saturday)',150,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-02-24 03:32:09','2026-06-24 02:14:02');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(42,37,'Mithora Regular Tiffin',replace(replace('Fresh homemade tiffin with 4 roti, sabzi, dal, rice, Salad. Light, healthy daily meals delivered hot. (Monday - Saturday)\r\n','\r',char(13)),'\n',char(10)),6700,7000,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-02-24 03:35:28','2026-02-24 03:55:34');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(43,37,'Mithora Delight Tiffin','Fresh homemade tiffin with 4 roti, 2 sabzi( Gravy & Dry ), dal, jeera rice, Salad, Raita/Chaas,Papad,Sweet. Light, healthy daily meals delivered hot. (Monday - Saturday)',7850,8200,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-02-24 03:36:21','2026-02-24 03:36:21');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(44,31,'Premium Festive',replace(replace('Per Person menu\r\n\r\n3-4 Ghee Roti • Rice • Paneer • Veg • Dal • Raita • Sweet • 1 Sweet','\r',char(13)),'\n',char(10)),250,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:19:22','2026-06-24 02:09:37');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(45,31,'Royal Celebration',replace(replace('Per Person menu \r\n\r\n3-4 Roti/Paratha • Rice/Pulao • 2 Premium Sabji • Dal • Full Sides • 1 Starters • 1 Sweet','\r',char(13)),'\n',char(10)),385,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:20:09','2026-06-24 02:09:37');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(46,38,'Dal Bati Diet Pack',replace(replace('✦ 20 Wood-fired Bati\r\n✦ Panchmel Dal\r\n✦ Lehsun Chutney\r\n✦ Fresh Salad\r\n✦ Mirchi Chatni','\r',char(13)),'\n',char(10)),1999,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:22:27','2026-03-10 02:22:27');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(47,38,'Rajasthani Best Choice',replace(replace('✦ 20 Desi Ghee Bati\r\n✦ Panchmel Dal\r\n✦ Shuddh Ghee Churma\r\n✦ Gatte ki Sabji\r\n✦ Lehsun Chutney','\r',char(13)),'\n',char(10)),2999,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:22:56','2026-03-10 02:22:56');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(48,38,'Royal Rajshahi Thali',replace(replace('✦ 20 Bati\r\n✦ Panchmel Dal\r\n✦ Special Churma\r\n✦ Ker Sangri\r\n✦ Gatte Ki Sabji\r\n✦ Kadhi\r\n✦ Chaas\r\n✦ Lehsun Chutney\r\n✦ Marwari Tipore','\r',char(13)),'\n',char(10)),3999,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:23:24','2026-03-10 02:23:24');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(49,39,'Sabudana Classics',replace(replace('Sabudana Khichdi:\r\nNon-sticky & peanut-rich.\r\nSabudana Vada:\r\nCrispy outside, soft inside.\r\nServed with fresh Chutney / Dahi.','\r',char(13)),'\n',char(10)),100,0,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:30:26','2026-03-10 02:30:26');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(50,40,'Premium Vrat Thali',replace(replace('3 Rajgiri / Kuttu Ki Roti:\r\nFreshly made.\r\nMain:\r\nVrat Wale Alloo Ki Sabji.\r\nSides:\r\nDahi & Sabudana Khichdi.\r\nDessert:\r\nShudh Alloo Ka Halwa.','\r',char(13)),'\n',char(10)),249,299,0,'local',0,0,'undefined','undefined',1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:32:40','2026-03-10 02:32:40');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(51,41,'Fastfood Light ( Per Pax )',replace(replace('Veg Mayonnaise Sandwich	1 Pc\r\nVeg Fried Momo	6 Pc\r\nPoha	1 Plate ( 250 Gm )\r\nMasala Sweet Corn	1 Person ( 100 Gm )\r\nAaloo Kofta	1 Pc','\r',char(13)),'\n',char(10)),225,0,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:42:02','2026-03-10 02:48:39');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(52,41,'Fastfood Delight ( Per Pax )',replace(replace('Veg Manchurian Gravy	3 Pc\r\nHoney Chilli Potato	150 Gm\r\nVeg Hakka Noodles	200 Gm\r\nPasta Red & White Sauce	1 Person(250 Gm )','\r',char(13)),'\n',char(10)),290,320,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:42:44','2026-03-10 02:48:45');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(53,41,'Fastfood Mithora Choice ( Per Pax )',replace(replace('Paneer Chilli	4-5 Pc\r\nVeg Momo	6 Pc\r\nVeg Fried Rice	1 Person ( 200 Gm )\r\nPani Patasha ( Golgappa )	10 Pc','\r',char(13)),'\n',char(10)),320,360,0,'local',0,0,0,0,1000,0,1,'none',0,0,NULL,NULL,1,'2026-03-10 02:43:36','2026-03-10 02:48:50');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(54,42,'Fresh Fruit Bowl','A hand-picked selection of Apple, Pomegranate, Papaya, Kiwi, and seasonal fruits like Mango. Topped with seeds.',99,120,0,'local',300,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-03-11 14:26:24','2026-03-11 14:26:24');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(55,43,'Fresh Healthy Sprouts','Protein-rich Moong and Chana sprouts prepared in our home kitchen. Mixed with lemon, onion, and mild spices.',99,135,0,'local',300,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-03-11 14:28:02','2026-03-11 14:28:02');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(56,44,'Pindi Chole & Paratha Combo','Punjabi-style pindi chole served with 2 freshly made ghee paratha  – bold, flavorful, and satisfying.',120,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-05-01 02:21:06','2026-05-01 02:21:06');
INSERT INTO "product_variants" ("id","product_id","variant_name","description","price","old_price","is_default","ship_type","weight_grams","length_cm","width_cm","height_cm","stock","max_per_order","min_order","slot_type","slot_cutoff_minutes","next_day_delivery","available_from_time","available_to_time","is_active","created_at","updated_at") VALUES(57,45,'Paneer Butter Masala Paratha Combo','Flavorful paneer butter masala with rich gravy, served with 2 warm paratha – a perfect comfort meal.',180,0,0,'local',0,0,'undefined','undefined',0,0,1,'none',0,0,NULL,NULL,1,'2026-05-01 02:22:37','2026-05-01 02:22:37');

PRAGMA foreign_keys = ON;
